#!/bin/sh

# PROVIDE: mycilium_orchestrator
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name=mycilium_orchestrator
rcvar=mycilium_enable
stop_cmd=mycilium_stop

load_rc_config $name

: ${mycilium_enable:="YES"}

pidfile="/var/run/site_${name}.pid"
procname=/usr/sbin/daemon
command=$procname
command_args="--change-dir \
  --sighup \
  --output-file /var/log/${name} \
  -P ${pidfile} \
  --restart \
  --title ${name} \
  --syslog-tag service_${name} \
  /usr/local/bin/pot start mycilium-orchestrator"

mycilium_stop() {
  kill -2 "$(cat $pidfile)"
  /usr/local/bin/pot stop -p $name
}

run_rc_command "$1"
